#!/bin/bash

# Confirm with user
read -n 1 -p "Push to GitHub? (enter or ctrl+c):" input


#Copy (sync?) files from /mnt/
printf "\033[0;32mCopying files...\033[0m\n"


#Perform git commit/push

# If a command fails then the deploy stops
set -e

printf "\033[0;32mDeploying updates to GitHub...\033[0m\n"

# Add changes to git
git add -A

# Commit changes
msg="rebuilding site $(date)"
if [ -n "$*" ]; then
	msg="$*"
fi
git commit -m "$msg"

# Push source
git push